#!/bin/bash
# Pre-commit hook to make a mysql dump right before committing and add it to the commit.
# 
## Change the following values to suit your local setup.
# The name of a database user with read access to the database.

. c:/home/ducksmanager/ducksmanager.properties

MYSQLPATH=c:/wamp/bin/mysql/mysql5.5.24/bin

DBUSER=root
# The password associated with the above user. Leave commented if none.
DBPASS=$db_password
# The database associated with this repository.
DBNAME=db301759616
# The path relative to the repository root in which to store the sql dump.
DBPATH=db
# The name of the export file
DBEXPORTNAME=structure_generale
# The regex filtering the tables whose structure is NOT fetched
DBTABLESEXCLUDED="^(edgecreator|tranches_en_cours|images_myfonts)"
 
[[ -d $DBPATH ]] || mkdir $DBPATH

$MYSQLPATH/mysqldump -d -u $DBUSER -p$DBPASS $DBNAME $($MYSQLPATH/mysql -u $DBUSER -p$DBPASS $DBNAME -Bse "SHOW TABLES WHERE Tables_in_$DBNAME NOT REGEXP '$DBTABLESEXCLUDED'") > $DBPATH/$DBEXPORTNAME.sql

git add $DBPATH/$DBEXPORTNAME.sql

exit 0