<?php
define('PM_373','La première invention de Géo Trouvetou');
define('PM_374','L\'île des  Menehunes');
define('PM_375','Picsou et le rêve d\'une vie');
define('PM_376','EN ROUTE POUR LE GRAND NORD');
define('PM_377','la guerre des windigos');
define('PM_378','Picsou et la Pierre Philosophale');
define('PM_379','Les mystères de l\'Atlantide');
define('PM_380','Un problème de taille');
define('PM_381','Donald au pays des maths et magie');
define('PM_382','Les cartes perdues de Christophe Colomb');
define('PM_383','LE CHATEAU DE LA REINE DES SIRENES');
define('PM_384','Une affaire de glace');
define('PM_385','Picsou et la bibliothèque perdue d\'Alexandrie');
define('PM_386','Picsou et le maître des canards');
define('PM_387','44 gags de Donald Duck');
define('PM_388','Fracture temporelle pour Donald!');
define('PM_390','Rencontre avec les Cracs-Badaboums');
define('PM_391','Le secret du Hondorica');
define('PM_392','Donald et l\'heure de l\'or');
define('PM_393','Picsou et le trésor des Templiers');
define('PM_394','Donald et la rivière de la terreur!');
define('PM_395','Picsou fête Noël à Disneyland!');
define('PM_396','DONALD FAIT DU RASAGE A RAPA NUI!');
define('PM_397','Picsou et le retour du Chevalier Noir');
define('PM_398','Picsou et les Rapetou dans les choux');
define('PM_399','Un puits de dollars pour les Rapetou');
define('PM_401','Le trésor aux 10 avatars');
define('PM_402','Les 7 Fantastiques (moins quatre) caballeros');
define('PM_404','L\'excentrique odyssée');
define('PM_405','Le tour du monde en 80 défis');
define('PM_406','A la recherche de la  Toison d\'Or!');
define('PM_407','Un coeur en or!');
define('PM_408','La chevauchée historique');
define('PM_409','Picsou contre Picasso!!!');
define('PM_410','Le roi Picsou 1er');
define('PM_411','Le trésor du Hollandais volant');
define('PM_412','La caroube des Caraïbes');
define('PM_413','Dans la vallée des volcans!');
define('PM_414','Les micro-duck de l\'espace!');
define('PM_415','La légende de Paul Bunyan');
define('PM_416','King Eldorado');
define('PM_417','La prisonnière dans la vallée de l\'Agonie Blanche...');
define('PM_418','Le perroquet qui comptait...');
define('PM_419','C.E.S.T.D.U.C.H.A.R.A.B.I.A.');
define('PM_420','Le secret du vieux château');
define('PM_421','Bombie le Zombie!');
define('PM_422','Juste un pauvre vieil homme pauvre...');
define('PM_423','La croisière des milliardaires');
define('PM_424','Touriste terrifiant!');
define('PM_425','Retour au Klondike');
define('PM_426','Un petit cadeau très spécial');
define('PM_427','Perdus dans les Andes');
define('PM_428','Le premier comic book de Géo Trouvetou');
define('PM_430','Sur un air de cha-cha-cha!!!');
define('PM_432','Le chevalier noir');
define('PM_433','Le loup-garou du grand nord');
define('PM_435','La bataille des fourmis géantes');
define('PM_437','50 coffres à casser!');
define('PM_439','La flamme olympique!');
define('PM_440','Le canard le plus pauvre de Donaldville!');
define('PM_441','Les 7 cités de Cibola');
define('PM_442','Le dernier voyage du capt\'ain Duck');
define('PM_443','Le radin dépensier !');
define('PM_444','Pour 100$ de moins...');
define('PM_445','Course dans les mers du Sud!');
define('PM_446','Bingo Bogo!');
define('PM_447','Piège à l\'héritage!');
define('PM_448','Le Tigre du Bengale!');
define('PM_449','Le fantôme de la grotte...');
define('PM_450','L\'anneau de la momie...');
define('PM_451','La Fondation Picsou');
define('PM_452','Les timbrés du timbre!');
define('PM_453','Bobos ou bonbons?');
define('PM_454','Mystère en sauce');
define('PM_455','La Lettre du Père Noël');
define('PM_456','La forêt mystérieuse');
define('PM_457','Le roi Picsou 1er');
define('PM_458','La jeunesse de Picsou n%C2%B01');
define('PM_459','1880-1882 Le roi du Mississippi');
define('PM_460','1882 Buck Picsou des Badlands');
define('PM_461','1883 Le cow-boy capitaine du Cutty Sark');
define('PM_463','1885 Le Nouveau Maître du manoir McPicsou');
define('PM_464','1887-1889 La Terreur du Transvaal');
define('PM_465','1890 Le Protecteur de Pizen Bluff');
define('PM_466','1893-1896 Le rêveur');
define('PM_466_2','du Never Never');

?>
